version: "3.8"

networks:
  my_network:   # Define a custom network
    driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_network   # Attach to the custom network

  achat-backend:
    image: hassenzayani/achat:v1.0-prod
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - my_network   # Attach to the custom network

  achat-frontend:
    image: hassenzayani/front:angular  # Replace with the actual image name/tag for your Angular frontend
    restart: unless-stopped
    ports:
      - 4201:80  # You can map port 80 of the host to the frontend container
    networks:
      - my_network   # Attach to the custom network

volumes:
  db:
