version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  achat-backend:
      image: ghiloufiw/ghiloufi:v1.0.0-prod
      restart: unless-stopped
      ports:
        - 8089:8089
      depends_on:
        - mysqldb

volumes:
  db:
