version: '3'

services:
  # MySQL database container
  mysql:
    image: mysql:5.7
    container_name: my-mysql-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Application container built from Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-test
    ports:
      - "8089:8089" # Use the same port as specified in your application.properties
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  .m2:
