my_container:
  depends_on:
    - mysqldb
  build:
    context: .
    dockerfile: Dockerfile
  image: devops-test:prod
  ports:
    - "8085:8085"
  volumes:
    - .m2:/root/.m2
  stdin_open: true
  tty: true
