version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backendNetwork
      
  springboot:
    image: amaniboussaa/springachat
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysqldb:3306"]
      interval: 10s
      retries: 5
    networks:
      - backendNetwork
      - frontendNetwork

  angular:
    image: amaniboussaa/angularachat
    ports:
      - 4200:80
    depends_on:
      - springboot
    networks:
      - frontendNetwork

volumes:
  db:

networks:
  backendNetwork:
  frontendNetwork:
