version: '3'

services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-test:prod
    ports:
      - "80:80"
    volumes:
      - .m2:/root/.m2
      
    stdin_open: true
    tty: true

