apiVersion: v1
kind: Namespace
metadata:
  name: achat-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: achat-backend
  labels:
    app: achat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achat-backend
  template:
    metadata:
      labels:
        app: achat-backend
    spec:
      containers:
        - name: achat-backend
          image: hassenzayani/achat:v1.0-prod
          ports:
            - containerPort: 8089
          env:
            - name: MYSQL_HOST
              value: mysql-service
---
apiVersion: v1
kind: Service
metadata:
  name: achat-backend-service
spec:
  selector:
    app: achat-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hassenzayani/front:angular
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
